drop database if exists terrashop;
create database terrashop;
use terrashop;

DROP TABLE IF EXISTS usuario;
CREATE TABLE USUARIO (
  ID_USUARIO bigint(20) NOT NULL AUTO_INCREMENT,
  APELLIDOS varchar(255) NOT NULL,
  BANCO varchar(255) DEFAULT NULL,
  CODIGO_SEGURIDAD int(20) DEFAULT NULL,
  CONTRASENA varchar(255) NOT NULL,
  DIRECCION_ENVIO varchar(255) DEFAULT NULL,
  DIRECCION_FACTURACION varchar(255) DEFAULT NULL,
  EMAIL varchar(255) DEFAULT NULL,
  NOMBRE varchar(255) NOT NULL,
  NUMERO_TARJETA int(20) DEFAULT NULL,
  TITULAR varchar(255) DEFAULT NULL,
  USUARIO varchar(255) NOT NULL UNIQUE,
  ROL varchar(255) DEFAULT 'CLIENTE',
  PRIMARY KEY (ID_USUARIO)
);

DROP TABLE IF EXISTS producto;
CREATE TABLE producto (
  ID_PRODUCTO bigint(20) NOT NULL AUTO_INCREMENT,
  NOMBRE varchar(255) NOT NULL,
  PRECIO float NOT NULL,
  STOCK int(11) NOT NULL,
  PRIMARY KEY (ID_PRODUCTO)
);