drop database if exists terrashop;
create database terrashop;
use terrashop;

DROP TABLE IF EXISTS rol;
CREATE TABLE ROL
(
   ID_ROL NOT NULL AUTO_INCREMENT,
   NOMBRE_ROL VARCHAR (40) NOT NULL,
   PRIMARY KEY (ID_ROL)
);

DROP TABLE IF EXISTS usuario;
CREATE TABLE USUARIO (
  ID_USUARIO bigint(20) NOT NULL AUTO_INCREMENT,
  APELLIDOS varchar(255) NOT NULL,
  BANCO varchar(255) DEFAULT NULL,
  CODIGO_SEGURIDAD int(20) DEFAULT NULL,
  PASSWORD varchar(255) NOT NULL,
  DIRECCION_ENVIO varchar(255) DEFAULT NULL,
  DIRECCION_FACTURACION varchar(255) DEFAULT NULL,
  EMAIL varchar(255) DEFAULT NULL,
  NOMBRE varchar(255) NOT NULL,
  NUMERO_TARJETA int(20) DEFAULT NULL,
  TITULAR varchar(255) DEFAULT NULL,
  USUARIO varchar(255) NOT NULL UNIQUE,
  ROL varchar(255) DEFAULT 'CLIENTE',
  PRIMARY KEY (ID_USUARIO)
);

DROP TABLE IF EXISTS usuario_rol;
CREATE TABLE USUARIO_ROL (
   ID_USUARIO INT NOT NULL,
   ID_ROL NOT NULL,
      PRIMARY KEY
   (
      ID_USUARIO,
      ID_ROL
   ),
   PRIMARY KEY (ID_ROL)
      CONSTRAINT FK_USUARIO_ROL_1 FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO) ON DELETE CASCADE,
	CONSTRAINT FK_USUARIO_ROL_2 FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL)
);

DROP TABLE IF EXISTS producto;
CREATE TABLE producto (
  ID_PRODUCTO bigint(20) NOT NULL AUTO_INCREMENT,
  NOMBRE varchar(255) NOT NULL,
  PRECIO float NOT NULL,
  STOCK int(11) NOT NULL,
  PRIMARY KEY (ID_PRODUCTO)
);